// batteries/backend-explorer/src/ui/components/LogEntry.tsx
import type { Log } from "@blazyts/blazy-edge";
import type { CSSProperties, FC } from "react";

import { useEffect, useMemo, useState } from "react";

import { MockLogsRepo } from "../../logs-repo/MockLogsRepo";

type LogEntryProps = {
  log: Log;
};

type WebSocketMessage = {
  type: "sent" | "received";
  data: unknown;
  timestamp: Date;
};

type RequestDetails = {
  method?: string;
  path?: string;
  headers?: Record<string, unknown>;
  body?: unknown;
  recievedAt?: string | number | Date;
};

type ResponseDetails = {
  statusCode?: number;
  body?: unknown;
  sentAt?: string | number | Date;
};

const monospaceFont = "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace";

const styles: Record<string, CSSProperties> = {
  entry: {
    background: "#1e293b",
    border: "1px solid #334155",
    borderRadius: 8,
    boxSizing: "border-box",
    marginBottom: 12,
    overflow: "hidden",
  },
  summary: {
    alignItems: "center",
    background: "#1e293b",
    cursor: "pointer",
    display: "flex",
    gap: 16,
    padding: 12,
  },
  badge: {
    borderRadius: 4,
    color: "#fff",
    display: "inline-block",
    fontWeight: 600,
    textAlign: "center",
  },
  statusBadge: {
    fontSize: 14,
    minWidth: 60,
    padding: "6px 12px",
  },
  methodBadge: {
    fontSize: 12,
    minWidth: 50,
    padding: "4px 8px",
  },
  path: {
    color: "#f1f5f9",
    flex: 1,
    fontFamily: monospaceFont,
    fontSize: 14,
    overflowWrap: "anywhere",
  },
  protocol: {
    background: "#0f172a",
    borderRadius: 4,
    color: "#94a3b8",
    fontSize: 12,
    padding: "0 8px",
  },
  time: {
    color: "#94a3b8",
    fontSize: 14,
    whiteSpace: "nowrap",
  },
  duration: {
    color: "#38bdf8",
    fontWeight: 600,
    minWidth: 64,
    textAlign: "right",
  },
  chevron: {
    color: "#94a3b8",
  },
  details: {
    background: "#0f172a",
    borderTop: "1px solid #334155",
    padding: 16,
  },
  detailSection: {
    marginBottom: 16,
  },
  detailHeading: {
    color: "#38bdf8",
    fontWeight: 600,
    margin: "0 0 8px",
  },
  detailRow: {
    alignItems: "flex-start",
    display: "flex",
    gap: 16,
    marginBottom: 8,
  },
  detailLabel: {
    color: "#94a3b8",
    fontWeight: 500,
    minWidth: 150,
  },
  detailValue: {
    color: "#f1f5f9",
    flex: 1,
    overflowWrap: "anywhere",
  },
  codeBlock: {
    background: "#1e293b",
    border: "1px solid #334155",
    borderRadius: 4,
    color: "#e2e8f0",
    display: "block",
    fontSize: 14,
    marginTop: 8,
    overflowX: "auto",
    padding: 12,
    width: "100%",
  },
  wsFilterList: {
    display: "flex",
    gap: 8,
    marginBottom: 12,
  },
  wsFilterButton: {
    background: "transparent",
    border: "1px solid #334155",
    borderRadius: 4,
    color: "#e2e8f0",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 600,
    padding: "4px 12px",
  },
  wsFilterAllActive: {
    background: "#1e293b",
    borderColor: "#475569",
  },
  wsFilterReceivedActive: {
    borderColor: "#38bdf8",
    boxShadow: "0 0 0 4px rgb(56 189 248 / 10%)",
  },
  wsFilterSentActive: {
    borderColor: "#34d399",
    boxShadow: "0 0 0 4px rgb(52 211 153 / 10%)",
  },
  wsMessageList: {
    background: "#1e293b",
    border: "1px solid #334155",
    borderRadius: 4,
    maxHeight: 384,
    overflowY: "auto",
    padding: 12,
  },
  wsMessage: {
    background: "#0f172a",
    border: "1px solid #334155",
    borderLeftWidth: 4,
    borderRadius: 4,
    marginBottom: 12,
    padding: 12,
  },
  wsMessageSent: {
    background: "rgb(16 185 129 / 5%)",
    borderLeftColor: "#10b981",
  },
  wsMessageReceived: {
    background: "rgb(14 165 233 / 5%)",
    borderLeftColor: "#0ea5e9",
  },
  wsMessageHeader: {
    alignItems: "center",
    display: "flex",
    gap: 16,
    justifyContent: "space-between",
  },
  wsMessageType: {
    background: "#1e293b",
    borderRadius: 4,
    fontSize: 12,
    fontWeight: 600,
    padding: "2px 8px",
  },
  wsMessageTypeSent: {
    background: "rgb(16 185 129 / 10%)",
    color: "#10b981",
  },
  wsMessageTypeReceived: {
    background: "rgb(14 165 233 / 10%)",
    color: "#0ea5e9",
  },
  mutedCopy: {
    color: "#94a3b8",
  },
  emptyState: {
    color: "#94a3b8",
    padding: 8,
    textAlign: "center",
  },
};

function getStatusBackground(statusCode: number) {
  if (statusCode < 300)
    return "#10b981";
  if (statusCode < 400)
    return "#06b6d4";
  if (statusCode < 500)
    return "#f59e0b";
  return "#f43f5e";
}

function getStatusColor(statusCode: number) {
  if (statusCode < 300)
    return "#10b981";
  if (statusCode < 400)
    return "#06b6d4";
  if (statusCode < 500)
    return "#f59e0b";
  return "#f43f5e";
}

function getMethodBackground(method: string) {
  const backgrounds: Record<string, string> = {
    GET: "#10b981",
    POST: "#0ea5e9",
    PUT: "#f59e0b",
    DELETE: "#f43f5e",
    PATCH: "#8b5cf6",
  };

  return backgrounds[method] || "#6b7280";
}

const LogEntry: FC<LogEntryProps> = ({ log }) => {
  const [expanded, setExpanded] = useState(false);
  const [wsMessages, setWsMessages] = useState<WebSocketMessage[] | null>(null);
  const [wsFilter, setWsFilter] = useState<"all" | "received" | "sent">("all");
  useEffect(() => {
    if (log.connectionId) {
      const repo = new MockLogsRepo();
      repo.getWebSocketMessages(log.connectionId).then(setWsMessages);
    }
  }, [log.connectionId]);

  const filteredWsMessages = useMemo(() => {
    if (!wsMessages)
      return null;
    if (wsFilter === "all")
      return wsMessages;
    return wsMessages.filter(m => m.type === wsFilter);
  }, [wsMessages, wsFilter]);

  const formatDuration = (ms: number) => {
    if (ms < 1000)
      return `${ms}ms`;
    return `${(ms / 1000).toFixed(2)}s`;
  };

  const requestReceived = log.requestReceived as RequestDetails;
  const responseSent = log.responseSent as ResponseDetails;
  const statusCode = responseSent.statusCode || 200;
  const method = requestReceived.method || "WS";
  const path = requestReceived.path || "";
  const protocol = requestReceived.headers?.Upgrade === "websocket" ? "WS" : "HTTP";
  const timestamp = requestReceived.recievedAt || new Date();
  const duration = responseSent.sentAt && requestReceived.recievedAt
    ? new Date(responseSent.sentAt).getTime() - new Date(requestReceived.recievedAt).getTime()
    : 0;

  return (
    <div style={styles.entry}>
      <div style={styles.summary} onClick={() => setExpanded(!expanded)}>
        <span style={{ ...styles.badge, ...styles.statusBadge, background: getStatusBackground(statusCode) }}>{statusCode}</span>
        <span style={{ ...styles.badge, ...styles.methodBadge, background: getMethodBackground(method) }}>{method}</span>
        <span style={styles.path}>{path}</span>
        <span style={styles.protocol}>{protocol}</span>
        <span style={styles.time}>{new Date(timestamp).toLocaleTimeString()}</span>
        <span style={styles.duration}>{formatDuration(duration)}</span>
        <span style={styles.chevron}>{expanded ? "▼" : "▶"}</span>
      </div>

      {expanded && (
        <div style={styles.details}>
          <div style={styles.detailSection}>
            <h4 style={styles.detailHeading}>Request</h4>
            <div style={styles.detailRow}>
              <span style={styles.detailLabel}>Method:</span>
              <span style={styles.detailValue}>{method}</span>
            </div>
            <div style={styles.detailRow}>
              <span style={styles.detailLabel}>Path:</span>
              <span style={styles.detailValue}>{path}</span>
            </div>
            {log.requestReceived?.headers && (
              <div style={styles.detailRow}>
                <span style={styles.detailLabel}>Headers:</span>
                <code style={styles.codeBlock}>{JSON.stringify(log.requestReceived.headers, null, 2)}</code>
              </div>
            )}
            {log.requestReceived?.body && (
              <div style={styles.detailRow}>
                <span style={styles.detailLabel}>Body:</span>
                <code style={styles.codeBlock}>{JSON.stringify(log.requestReceived.body, null, 2)}</code>
              </div>
            )}
          </div>

          <div style={styles.detailSection}>
            <h4 style={styles.detailHeading}>Response</h4>
            <div style={styles.detailRow}>
              <span style={styles.detailLabel}>Status Code:</span>
              <span style={{ ...styles.detailValue, color: getStatusColor(statusCode), fontWeight: 600 }}>{statusCode}</span>
            </div>
            <div style={styles.detailRow}>
              <span style={styles.detailLabel}>Duration:</span>
              <span style={styles.detailValue}>{formatDuration(duration)}</span>
            </div>
            {log.responseSent?.body && (
              <div style={styles.detailRow}>
                <span style={styles.detailLabel}>Body:</span>
                <code style={styles.codeBlock}>{JSON.stringify(log.responseSent.body, null, 2)}</code>
              </div>
            )}
          </div>

          {log.connectionId && wsMessages && (
            <div style={styles.detailSection}>
              <h4 style={styles.detailHeading}>
                WebSocket Messages (
                {wsMessages.length}
                )
              </h4>

              <div style={styles.wsFilterList}>
                <button
                  style={{ ...styles.wsFilterButton, ...(wsFilter === "all" ? styles.wsFilterAllActive : {}) }}
                  onClick={() => setWsFilter("all")}
                  aria-pressed={wsFilter === "all"}
                >
                  All
                </button>
                <button
                  style={{ ...styles.wsFilterButton, ...(wsFilter === "received" ? styles.wsFilterReceivedActive : {}) }}
                  onClick={() => setWsFilter("received")}
                  aria-pressed={wsFilter === "received"}
                >
                  Received
                </button>
                <button
                  style={{ ...styles.wsFilterButton, ...(wsFilter === "sent" ? styles.wsFilterSentActive : {}) }}
                  onClick={() => setWsFilter("sent")}
                  aria-pressed={wsFilter === "sent"}
                >
                  Sent
                </button>
              </div>

              <div style={styles.wsMessageList}>
                {(filteredWsMessages || [])
                  .filter(msg => msg.type === wsFilter || wsFilter === "all")
                  .map((msg, idx) => (
                    <div key={`${msg.timestamp.toString()}-${idx}`} style={{ ...styles.wsMessage, ...(msg.type === "sent" ? styles.wsMessageSent : styles.wsMessageReceived) }}>
                      <div style={styles.wsMessageHeader}>
                        <span style={{ ...styles.wsMessageType, ...(msg.type === "sent" ? styles.wsMessageTypeSent : styles.wsMessageTypeReceived) }}>
                          {msg.type === "sent" ? " Sent " : " Received "}
                        </span>
                        <span style={styles.mutedCopy}>{new Date(msg.timestamp).toLocaleTimeString()}</span>
                      </div>
                      {msg.data && Object.keys(msg.data).length > 0 && (
                        <code style={styles.codeBlock}>{JSON.stringify(msg.data, null, 2)}</code>
                      )}
                    </div>
                  ))}
                {filteredWsMessages && filteredWsMessages.length === 0 && (
                  <div style={styles.emptyState}>No messages match the filter.</div>
                )}
              </div>
            </div>
          )}

          <div style={styles.detailSection}>
            <h4 style={styles.detailHeading}>Metadata</h4>
            <div style={styles.detailRow}>

              <span style={styles.detailLabel}>Request ID:</span>
              <span style={styles.detailValue}>{log.requestId}</span>
            </div>
            <div style={styles.detailRow}>
              <span style={styles.detailLabel}>Received At:</span>
              <span style={styles.detailValue}>{new Date(timestamp).toLocaleString()}</span>
            </div>
            <div style={styles.detailRow}>
              <span style={styles.detailLabel}>Sent At:</span>
              <span style={styles.detailValue}>{log.responseSent?.sentAt ? new Date(log.responseSent.sentAt).toLocaleString() : "N/A"}</span>
            </div>
            {log.connectionId && (
              <div style={styles.detailRow}>
                <span style={styles.detailLabel}>Connection ID:</span>
                <span style={styles.detailValue}>{log.connectionId}</span>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default LogEntry;

// batteries/logs-viewer/h/src/components/LogEntry.vue
<script setup lang="ts">
import { ref } from 'vue';
import type { Log } from '@blazyts/blazy-edge';

defineProps({
  log: {
    type: Object as () => Log,
    required: true,
  },
});

const expanded = ref(false);

const getStatusClass = (statusCode: number) => {
  if (statusCode < 300) return 'status-2xx';
  if (statusCode < 400) return 'status-3xx';
  if (statusCode < 500) return 'status-4xx';
  return 'status-5xx';
};

const getMethodClass = (method: string) => {
  const classes: Record<string, string> = {
    GET: 'method-get',
    POST: 'method-post',
    PUT: 'method-put',
    DELETE: 'method-delete',
    PATCH: 'method-patch',
  };
  return classes[method] || 'method-default';
};

const formatDuration = (ms: number) => {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(2)}s`;
};
</script>

<template>
  <div class="log-entry">
    <div class="log-header" @click="expanded = !expanded">
      <span :class="['status-badge', getStatusClass(log.statusCode)]">
        {{ log.statusCode }}
      </span>

      <span :class="['method-badge', getMethodClass(log.method)]">
        {{ log.method }}
      </span>

      <span class="log-path">{{ log.path }}</span>

      <span class="log-protocol">{{ log.protocol }}</span>

      <span class="log-timestamp">{{ new Date(log.timestamp).toLocaleTimeString() }}</span>

      <span class="log-duration">{{ formatDuration(log.duration) }}</span>

      <span class="expand-icon">{{ expanded ? '▼' : '▶' }}</span>
    </div>

    <div v-if="expanded" class="log-details">
      <div class="detail-section">
        <h4>Request</h4>
        <div class="detail-group">
          <span class="label">Method:</span>
          <span class="value">{{ log.method }}</span>
        </div>
        <div class="detail-group">
          <span class="label">Path:</span>
          <span class="value">{{ log.path }}</span>
        </div>
        <div class="detail-group">
          <span class="label">Protocol:</span>
          <span class="value">{{ log.protocol }}</span>
        </div>
        <div v-if="log.queryParams" class="detail-group">
          <span class="label">Query Params:</span>
          <code class="value">{{ JSON.stringify(log.queryParams, null, 2) }}</code>
        </div>
        <div v-if="log.headers" class="detail-group">
          <span class="label">Headers:</span>
          <code class="value">{{ JSON.stringify(log.headers, null, 2) }}</code>
        </div>
      </div>

      <div class="detail-section">
        <h4>Response</h4>
        <div class="detail-group">
          <span class="label">Status Code:</span>
          <span :class="['value', getStatusClass(log.statusCode)]">{{ log.statusCode }}</span>
        </div>
        <div class="detail-group">
          <span class="label">Duration:</span>
          <span class="value">{{ formatDuration(log.duration) }}</span>
        </div>
        <div v-if="log.responseBody" class="detail-group">
          <span class="label">Response Body:</span>
          <code class="value">{{ JSON.stringify(log.responseBody, null, 2) }}</code>
        </div>
        <div v-if="log.errorMessage" class="detail-group error">
          <span class="label">Error:</span>
          <span class="value">{{ log.errorMessage }}</span>
        </div>
      </div>

      <div class="detail-section">
        <h4>Metadata</h4>
        <div class="detail-group">
          <span class="label">Timestamp:</span>
          <span class="value">{{ new Date(log.timestamp).toLocaleString() }}</span>
        </div>
        <div class="detail-group">
          <span class="label">User Agent:</span>
          <span class="value">{{ log.userAgent || 'N/A' }}</span>
        </div>
        <div class="detail-group">
          <span class="label">IP Address:</span>
          <span class="value">{{ log.ipAddress || 'N/A' }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.log-entry {
  border: 1px solid var(--color-border);
  border-radius: 0.5rem;
  margin-bottom: 0.75rem;
  overflow: hidden;
}

.log-header {
  display: flex;
  align-items: center;
  gap: 1rem;
  padding: 1rem;
  background-color: var(--color-bg-secondary);
  cursor: pointer;
  transition: background-color 0.2s;
}

.log-header:hover {
  background-color: var(--color-bg);
}

.status-badge {
  min-width: 60px;
  padding: 0.375rem 0.75rem;
  border-radius: 0.375rem;
  font-weight: 600;
  font-size: 0.875rem;
  text-align: center;
  color: white;
}

.status-2xx {
  background-color: var(--color-status-2xx);
}

.status-3xx {
  background-color: var(--color-status-3xx);
}

.status-4xx {
  background-color: var(--color-status-4xx);
}

.status-5xx {
  background-color: var(--color-status-5xx);
}

.method-badge {
  min-width: 50px;
  padding: 0.375rem 0.5rem;
  border-radius: 0.375rem;
  font-weight: 600;
  font-size: 0.75rem;
  text-align: center;
  color: white;
}

.method-get {
  background-color: #10b981;
}

.method-post {
  background-color: #3b82f6;
}

.method-put {
  background-color: #f59e0b;
}

.method-delete {
  background-color: #ef4444;
}

.method-patch {
  background-color: #8b5cf6;
}

.method-default {
  background-color: #6b7280;
}

.log-path {
  flex: 1;
  font-family: 'Monaco', 'Courier New', monospace;
  font-size: 0.9rem;
  color: var(--color-text);
  word-break: break-all;
}

.log-protocol {
  padding: 0.25rem 0.5rem;
  background-color: var(--color-bg);
  border-radius: 0.25rem;
  font-size: 0.75rem;
  color: var(--color-text-secondary);
}

.log-timestamp {
  font-size: 0.85rem;
  color: var(--color-text-secondary);
  white-space: nowrap;
}

.log-duration {
  font-weight: 600;
  color: var(--color-primary);
  min-width: 60px;
  text-align: right;
}

.expand-icon {
  color: var(--color-text-secondary);
  transition: transform 0.2s;
}

.log-header:hover .expand-icon {
  color: var(--color-primary);
}

.log-details {
  background-color: var(--color-bg);
  border-top: 1px solid var(--color-border);
  padding: 1.5rem;
}

.detail-section {
  margin-bottom: 1.5rem;
}

.detail-section:last-child {
  margin-bottom: 0;
}

.detail-section h4 {
  margin: 0 0 0.75rem 0;
  font-size: 0.95rem;
  font-weight: 600;
  color: var(--color-primary);
}

.detail-group {
  display: flex;
  gap: 1rem;
  margin-bottom: 0.75rem;
  align-items: flex-start;
}

.detail-group.error {
  color: var(--color-status-5xx);
}

.detail-group .label {
  min-width: 150px;
  font-weight: 500;
  color: var(--color-text-secondary);
  flex-shrink: 0;
}

.detail-group .value {
  flex: 1;
  color: var(--color-text);
  word-break: break-word;
}

.detail-group code {
  display: block;
  width: 100%;
  background-color: var(--color-bg-secondary);
  padding: 0.75rem;
  border-radius: 0.375rem;
  border: 1px solid var(--color-border);
  font-size: 0.85rem;
  overflow-x: auto;
  margin-top: 0.5rem;
}

@media (max-width: 768px) {
  .log-header {
    flex-wrap: wrap;
    gap: 0.5rem;
  }

  .log-path {
    flex: 1 0 100%;
  }

  .log-timestamp {
    flex: 1 0 50%;
  }

  .log-duration {
    flex: 1 0 50%;
  }

  .detail-group {
    flex-direction: column;
    gap: 0.25rem;
  }

  .detail-group .label {
    min-width: auto;
  }
}
</style>
